/* 
 * Swagger Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;

namespace IO.Swagger.Client
{
	/// <summary>
	/// HttpResponseMessage helper
	/// </summary>
	public static class ResponseExtension
	{
		/// <summary>
		/// HttpResponseMessage headers to IDictionary convertion
		/// </summary>
		public static IDictionary<string, string> ToHeaders(this HttpResponseMessage value)
		{
			return value.Headers.ToDictionary(x => x.Key, x => string.Join("", x.Value));
		}
	}
}
